server:
  port: 8050
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone:
        http://localhost:8761/eureka/
spring:
  application:
    name: gateway-zuul
zuul:
  routes:
    # 和 routes 的 key 相同，可以省略，也就是可以配置成： eureka-user-order-1: /t/**
    # 此时访问 http://localhost:8500/t/order/1,相当于访问 http://localhost:8500/eureka-user-order-1/order/1
    eureka-user-order-1:
      path: /t/**
      service-id: eureka-user-order-1
    # 此种代理不会使用 eureka Ribbon 的客户端均衡和 hystrix 的 断路器，但是可以配置成使用
    # 此时访问 http://localhost:8500/g/order/1,相当于访问 http://localhost:7900/order/1
    order-url-122:
      path: /g/**
      url: http://localhost:7900/